### ISSUE TITLE
Projecting onto multiple parts

### ISSUE THREAD

**Issue by drewcassidy** [drewcassidy/KSP-Conformal-Decals#22]
Currently decals can only project onto one part at a time (the part's parent). It should be possible to allow projection onto all parts that intersect its bounds. Related to #3

**Comment by drewcassidy** [comment]
Added a naive implementation that slows down with complicated crafts, will likely revisit in future

**Comment by dodecadevin** [comment]
is this one of the features that was reverted in 0.2.12? it doesn't seem to be functioning, at least for me

**Comment by drewcassidy** [comment]
It has never been shipped in a released version

**Comment by dodecadevin** [comment]
Ohhhhh my bad, i'm really not GitHub-savvy! Thanks for the work!
