### ISSUE TITLE
Characters not from Latin Alphabet break Text Decal

### ISSUE THREAD

**Issue by StonesmileGit** [drewcassidy/KSP-Conformal-Decals#24]
Text not from the latin alphabet doesn't get saved or handled correctly.

Tested with Cyrillic and Greek Alphabet.

**Comment by drewcassidy** [comment]
hmm, I swear I tested that. will check it out

**Comment by StonesmileGit** [comment]
The issue was noticed on KSP 1.8, not sure if relevant.

**Comment by drewcassidy** [comment]
Have you been able to reproduce this with fonts other than Calibri?

**Comment by StonesmileGit** [comment]
Changing the font got the text to update, but when you save the vessel and reload the text gets reset. Other settings didn't update until you changed the font.

**Comment by StonesmileGit** [comment]
Working on the assumption that all .dll's were recompiled correctly after the recent commits:

Using Master causes a crash when trying to rename a vessel (at the top of the screen in the VAB)
Thought this fits here since the commits are related to this issue.

**Comment by drewcassidy** [comment]
try again now, I accidentally made a recursive font while troubleshooting

**Comment by StonesmileGit** [comment]
Issue seems to be fixed!
