### ISSUE TITLE
Release 0.2.8 Can't Simply Overwrite GameData Directory

### ISSUE THREAD

**Issue by JustaSimpleUser** [drewcassidy/KSP-Conformal-Decals#34]
Attempted to update from 0.2.7 to 0.2.8.  Downloaded the new repo and copied zip file's GameData into the KSP directory.  Started the game and immediately received an error stating that Harmony was improperly installed in GameDate\Shabby\Plugins and properly installed in GameData\000_Harmony.

![image](https://user-images.githubusercontent.com/13194658/126056702-45cfefc6-3c90-47e9-a07e-d57c01af577c.png)

I solved the problem by deleting the Shabby folder and restarted the game.  No startup errors this time but on entering the save game, any vessel with a conformal flag failed to load.

Reverted the GameData directory, removed 000_Harmony and reinstalled 0.2.7.

Unless I've completely screwed up the update, I suggest that there should be a warning about corrupting a save that contains exiting conformal flags or the conflict that results in deleted vessels after updating should be resolved.

**Comment by drewcassidy** [comment]
I don't know why you thought overwriting gamedata was a good idea to begin with?

**Comment by JustaSimpleUser** [comment]
Isn't that what one is supposed to do when installing a mod, i.e. copy the zip file's GameData over the install's GameData to ensure that all components of the mod are installed?

I thought that's exactly what the standard practice is.  Is your mod unique in some way?
