### ISSUE TITLE
Multiple Issues with Decal Symmetry

### ISSUE THREAD

**Issue by drewcassidy** [drewcassidy/KSP-Conformal-Decals#36]
This is an umbrella issue for multiple issues involving decal symmetry (#33 #35, etc). In order to tackle these issues once and for all, I need detailed descriptions of the ways in which these parts are breaking. Please leave a reply below with *detailed* instructions on how to reproduce a symmetry bug. For example: 

1) place text decal in 2x symmetry
2) change text color
3) text is now broken (with attached picture).

Thanks!

Bugs here:
- [x] Updating text that's in symmetry breaks state (fixed in 495441be06ea41d872fa0fe516df145f2b1319b4)

**Comment by bofhgr** [comment]
I'm using RP1 install with 1.10

steps to reproduce the missing text bug:
place a payload adapter and then add 2x symmetry procedural payload fairings. 
add text decal to the payload fairing, again in 2x symmetry
save the thing as a subassembly
re-load the vab and create a dummy payload then add the subassembly created preciously.
right click on the decal and you'll notice the text disappears while the text editor is open
edit the text and you'll notice the original decal no longer displays any text but the symmetry part displays the expected result.

I've been using the nasalization font and typically have 4 lines of text on this decal for the payload fairing (if that plays any role).

**Comment by drewcassidy** [comment]
@bofhgr For my future self: simpified recreation steps:
RP1 is unnecessary, nor is loading a subassembly. you just need to try to set the text of a decal in symmetry. No idea how I never spotted this when debugging before. oops!

**Comment by drewcassidy** [comment]
Text not updating in symmetry has been fixed in commit 495441be06ea41d872fa0fe516df145f2b1319b4. If anyone wants to try it just download the dll at that commit and replace the one in gamedata

**Comment by drewcassidy** [comment]
Looks like this was the only outstanding issue. Any more symmetry bugs can be reported as new issues
