### ISSUE TITLE
Old Versions of 0Harmony.dll and Shabby.dll

### ISSUE THREAD

**Issue by JustaSimpleUser** [drewcassidy/KSP-Conformal-Decals#37]
When I drop the Conformal-Decals GameData into my install, KSP 1.12.3 complains of old versions of these two files and a bad installation of 0Harmony which should only appear in the folder GameData\000_Harmony

Latest versions of Harmony is 1.2.0.1 contained in the latest Shabby 0.1.2.0.

**Comment by drewcassidy** [comment]
You have an old version of Shabby. The one bundled should be 0.2.0 and include Harmony 2 (NOT harmony 1 which is incompatible)

**Comment by JustaSimpleUser** [comment]
I installed via CKAN and the problem went away.
