### ISSUE TITLE
Since update, flags/text not visible

### ISSUE THREAD

**Issue by JordanMilly** [drewcassidy/KSP-Conformal-Decals#39]
Since the update earlier, all existing decals went blank, and when new ones are put on, while they are visible while placing them, once placed they also show as blank/invisible.

**Comment by drewcassidy** [comment]
Im not able to reproduce this. please include a log file

**Comment by drewcassidy** [comment]
is this still the case with the latest update?

**Comment by JordanMilly** [comment]
The new update fixed it, cheers @drewcassidy :)
