### ISSUE TITLE
"Select Subtype" UI: if bigger than screen height, cannot close it, locks whole VAB workflow

### ISSUE THREAD

**Issue by Gordon-Dry** [drewcassidy/KSP-Conformal-Decals#40]
Please make it either possible to scroll the UI up and down via mouse wheel to get a grip to the close button and/or toggle the UI off again using the same PAW button that was used to toggle it on.

Actuall I cannot interact with any other stock VAB UI element than that "Select Subtype" menu and those other non-stock UI elements you see on my screenshot:
![Screen-2022-11-21_17-06-02](https://user-images.githubusercontent.com/29145213/203102557-233de2f4-f8df-418f-ae6a-5434985943f6.jpg)

Pressing ESC closed the UI, though. If not, that would even have been worse.

**Comment by drewcassidy** [comment]
Not a conformal decals bug

**Comment by Gordon-Dry** [comment]
Is that UI not opened by that mod?
Please explain why, with a short sentence.

**Comment by drewcassidy** [comment]
That UI is part of B9 Part Switch

I think you can close it with escape
