### ISSUE TITLE
Please add camera tracking dot decals

### ISSUE THREAD

**Issue by Gordon-Dry** [drewcassidy/KSP-Conformal-Decals#41]
Like here:
https://images.foxtv.com/static.fox13news.com/www.fox13news.com/content/uploads/2022/08/932/524/ksc-20220421-ph-jbs01_0035large.jpg?ve=1&tl=1

**Comment by drewcassidy** [comment]
https://github.com/drewcassidy/KSP-Conformal-Decals/wiki/Making-Your-Own-Decals

**Comment by Gordon-Dry** [comment]
Like this would not be basic stuff but some weird wish.

**Comment by Gordon-Dry** [comment]
Okay, well, could it be that
GameData\ConformalDecals\Parts\Munar\Munar-Atlas.dds
already contains such decals but
GameData\ConformalDecals\Parts\Munar\decal-munar.cfg
does not refer to all of them?

I see one at x 280, y 0 but it's not referred.
So I assume there are more.
Never finished?
